### ISSUE TITLE
Category Navigation

### ISSUE THREAD

**Issue by makarovaiuliia** [makarovaiuliia/kickflip#28]
## Related issues in RS task

- [x] [Issue RSS-ECOMM-3_08: Implement Category 🏷️ and Breadcrumb Navigation](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint3/RSS-ECOMM-3_08.md)

## Tasks
- [x] create Bread crumbs component
- [x] Create labels for each gender
- [x] Sort sneakers according to gender
